version: '3.8'

services:
  db:
    image: postgres:15
    container_name: go_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: go_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go_network

volumes:
  pgdata:

networks:
  go_network:
    driver: bridge